name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ./.github/actions/setup-node-pnpm

      - name: Format check
        run: pnpm run fmt:check

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ./.github/actions/setup-node-pnpm

      - name: Lint
        run: pnpm run lint:check

  type:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ./.github/actions/setup-node-pnpm

      - name: Type check
        run: pnpm run type:check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - uses: ./.github/actions/setup-node-pnpm

      - name: Test
        run: pnpm run test
