name: GitHub Star Notifier
on:
  schedule:
    # 15分ごとに実行
    - cron: '0/15 * * * *'
  workflow_dispatch:
jobs:
  github-star-notifier:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: github-star-notifier
    # 15分以上かかったらタイムアウト
    timeout-minutes: 15
    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Denoのセットアップ
      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x
      # 必要なディレクトリの作成
      - name: Create directories
        run: mkdir -p data temp
      # 最終実行時刻のキャッシュを復元
      - name: Restore timestamp cache
        id: restore_cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: github-star-notifier/data/.timestamp
          key: github-star-notifier-timestamp
          restore-keys: github-star-notifier-timestamp-
      # dotenvxのインストール
      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh
      # Denoの実行
      - name: Run notifier
        run: dotenvx run -- deno run -A main.ts
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY_GITHUB_STAR_NOTIFIER }}
      # 最終実行時刻のキャッシュを保存
      - name: Save timestamp cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: always()
        with:
          path: github-star-notifier/data/.timestamp
          key: github-star-notifier-timestamp
