name: Link Insight Notifier
on:
  workflow_dispatch:
    inputs:
      link:
        description: 'LINK'
        required: true
jobs:
  link-insight-notifier:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: link-insight-notifier
    # 15分以上かかったらタイムアウト
    timeout-minutes: 15
    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      # Chromeのセットアップ
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@c785b87e244131f27c9f19c1a33e2ead956ab7ce # v1.7.3
        with:
          chrome-version: latest
      # Denoのセットアップ
      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x
      # dotenvxのインストール
      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh
      # Denoの実行
      - name: Deno Run
        run: |
          dotenvx run -- deno run -A main.ts
          ls -la
        env:
          DOTENV_PRIVATE_KEY: ${{secrets.DOTENV_PRIVATE_KEY_LINK_INSIGHT_NOTIFIER}}
          LINK: ${{github.event.inputs.link}}
