name: Link Insight Notifier
on:
  workflow_dispatch:
    inputs:
      link:
        description: 'LINK'
        required: true
jobs:
  link-insight-notifier:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: link-insight-notifier
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Setup Chrome
        id: setup_chrome
        uses: browser-actions/setup-chrome@73954683cc80eced513145a42b668b9b91f753c3 # v2.1.2
        with:
          chrome-version: latest
      - name: Verify Chrome
        run: '${{ steps.setup_chrome.outputs.chrome-path }} --version'
      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@2dec1e33f4ab2c6d5bce1b0c4607961bb1a3f7a1 # v1.12.0
        with:
          node-version-file: '.node-version'
          version: '0.2.1'
          cache: true
          run-install: false
      - name: Install dependencies
        run: vp install --frozen-lockfile
        working-directory: ${{ github.workspace }}
      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh
      - name: Run notifier
        run: |
          dotenvx run -- pnpm start
          ls -la
        env:
          DOTENV_PRIVATE_KEY: ${{secrets.DOTENV_PRIVATE_KEY_LINK_INSIGHT_NOTIFIER}}
          LINK: ${{github.event.inputs.link}}
          CHROME_PATH: ${{ steps.setup_chrome.outputs.chrome-path }}
