name: Monthly Housekeeping
on:
  schedule:
    # 毎月1日に実行
    - cron: '0 0 1 * *'
  workflow_dispatch:
jobs:
  monthly-housekeeping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Git setting
        run: |
          git pull
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit and push
        run: |
          git commit --allow-empty -m "chore: prevent automatic workflow stopping"
          git push
