name: RSS Feed Notifier

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  rss-feed-notifier:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: rss-feed-notifier
    timeout-minutes: 15

    steps:
      # リポジトリのチェックアウト
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # Denoのセットアップ
      - name: Setup Deno
        uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: v2.x

      # 必要なディレクトリの作成
      - name: Create directories
        run: mkdir -p data temp

      # タイムスタンプキャッシュの復元
      - name: Restore timestamp cache
        id: restore_timestamp
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: rss-feed-notifier/data/.timestamp
          key: rss-feed-notifier-timestamp-${{ github.run_id }}
          restore-keys: |
            rss-feed-notifier-timestamp-

      # アイテムリストキャッシュの復元
      - name: Restore item list cache
        id: restore_itemlist
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: rss-feed-notifier/data/.itemList.json
          key: rss-feed-notifier-itemlist-${{ github.run_id }}
          restore-keys: |
            rss-feed-notifier-itemlist-

      # dotenvxのインストール
      - name: Install dotenvx
        run: curl -sfS https://dotenvx.sh/install.sh | sh

      # Denoの実行
      - name: Run notifier
        run: dotenvx run -- deno run -A main.ts
        env:
          DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY_RSS_FEED_NOTIFIER }}

      # タイムスタンプキャッシュの保存
      - name: Save timestamp cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: always()
        with:
          path: rss-feed-notifier/data/.timestamp
          key: rss-feed-notifier-timestamp-${{ github.run_id }}

      # アイテムリストキャッシュの保存
      - name: Save item list cache
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        if: always()
        with:
          path: rss-feed-notifier/data/.itemList.json
          key: rss-feed-notifier-itemlist-${{ github.run_id }}
